### ISSUE TITLE
Add thread name to output

### ISSUE THREAD

**Issue by normanr** [haypo/faulthandler#18]
I'm not sure if it would be possible to add the name of the thread to the output.  It seems that the thread name is only stored in the python thread object which I don't think is accessible from native c.

(Feel free to close the issue if you think it's not feasible)

**Comment by haypo** [comment]
Are you talking  about this name? https://docs.python.org/dev/library/threading.html#threading.Thread.name

This one is a property on threading.Thread._name, a pure Python object. It's *not* possible to read it in faulthandler. You should prepare some logs somewhere when threads are created to log a mapping thread identifier => thread name, before you application does crash.

It's very risky to use introspection in C since faulthandler is called from a C signal handler. For example, you cannot use allocation on the heap (malloc) or you can get a dead lock.
