### ISSUE TITLE
Date&Time in the traceback output

### ISSUE THREAD

**Issue by cowo78** [haypo/faulthandler#19]
Hi all
do you think it would be useful to have date&time printed along with the traceback header? clock_gettime()?

**Comment by haypo** [comment]
Hi,

It may be possible to read a timestamp but not to format it with the classic nice format "Wed Feb  3 14:30:28 CET 2016", since formatting functions are too complex to be called from a signal handler.

Are you using faulthandler to retrieve a traceback on a crash? Or do you use a "safe" signal like SIGUSR1 and send manually the signal?

Only very few functions are async-signal safe and so can be used in faulthandler.

Victor

**Comment by cowo78** [comment]
I was thinking about something simpler, like the usual time() retval. After all it's just to have an idea about when the SEGV happened.
Yes, I'm using the module to have a traceback on SEGV.
The "async-safe" is fine for time() since it's explicitly listed in signal(7) but I don't know about clock_gettime(). At any rate I did not read any implementation and I don't know what could possibly go wrong. For sure it modifies errno.

**Comment by haypo** [comment]
> I was thinking about something simpler, like the usual time() retval
> (...) it's explicitly listed in signal(7)

Oh ok, in this case, it can work. You may have to write a new "write"
function for time_t.

> but I don't know about clock_gettime()

clock_gettime() can be interesting to get other clocks like monotonic
clock, but since logs are read by humans, time() UTC timestamp is
better.

Can you please propose a pull request to add "at time xxx" to the
first line of faulthandler?

**Comment by haypo** [comment]
Sorry, but this project is now a only backport for Python 2.7. I suggest you to propose a CPython pull requets to implement this feature. I now only make minimum work to maintain this backport.
