### ISSUE TITLE
Add custom header to faulthandler output

### ISSUE THREAD

**Issue by tailhook** [haypo/faulthandler#8]
Hi,

While debugging using faulthandler we have got a problem of matching PIDs with the tracebacks. So it would be nice if functions `dump_traceback_later` and `enable` had an optional parameter e.g. `header` which is printed before normal header (`Timeout(...)` or `Fatal  Python error`). Before you ask, yes I'll format string before installing header, and never fork after.

**Comment by tailhook** [comment]
Ping @haypo. What do you think? Will you accept a patch if I'll implement the feature?

**Comment by haypo** [comment]
> What do you think?

I understand your use case, I agree that there is an issue if two processes are logging into the same file.

> Will you accept a patch if I'll implement the feature?

Sure. It should easy to implement it. Don't forget an unit test.

faulthandler is now part of Python. You may propose the patch to Python directly. Otherwise, I can do the change in Python directly.

**Comment by haypo** [comment]
This project is a backport for Python 2.7. I suggest to propose a pull request on CPython upstream, new features occur there. I only make minimum work to maintain this backport.
